# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b566e6d0ca0852df9a964efe32cbcb986d6db1bd87344d1d9eda1f03f1dcc703169bd6e51a5a607f14e8e85cddd5a0256c44b7026f4a94e26e47e04414c07ab

test:
  secret_key_base: f6d13973536b6f0167c4c1c44d7e65c5a04fa946225a617c2daa02462f27baaaa8b0d28d683e7862a007b15d43222042631572bb24ca835b42e575ca46aceb18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
